export const LEDGER_ACCOUNT_CODES = {
  CUSTOMER_RECEIVABLE: 'CUSTOMER_RECEIVABLE',
  PLATFORM_ESCROW: 'PLATFORM_ESCROW',
  MERCHANT_PAYABLE: 'MERCHANT_PAYABLE',
  RIDER_PAYABLE: 'RIDER_PAYABLE',
  WALLET_LIABILITY: 'WALLET_LIABILITY',
  REFUND_EXPENSE: 'REFUND_EXPENSE',
  PROMOTION_EXPENSE: 'PROMOTION_EXPENSE',
  PLATFORM_COMMISSION: 'PLATFORM_COMMISSION',
  DELIVERY_REVENUE: 'DELIVERY_REVENUE',
  GST_PAYABLE: 'GST_PAYABLE',
  COD_COLLECTED: 'COD_COLLECTED',
} as const;

export type LedgerAccountCode = (typeof LEDGER_ACCOUNT_CODES)[keyof typeof LEDGER_ACCOUNT_CODES];
