packages:
  - "apps/*"
  - "packages/*"
overrides:
  '@types/react': ~19.1.17
  '@types/react-dom': ~19.1.11
allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  argon2: true
  bcrypt: true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
