/**
 * Domain event type constants — mirrors the Prisma DomainEventType enum.
 * Using a plain enum here decouples the application layer from Prisma's generated client.
 */
export enum DomainEventType {
  // Auth
  USER_REGISTERED = 'USER_REGISTERED',
  USER_LOGGED_IN = 'USER_LOGGED_IN',
  USER_LOGGED_OUT = 'USER_LOGGED_OUT',
  OTP_REQUESTED = 'OTP_REQUESTED',
  OTP_VERIFIED = 'OTP_VERIFIED',
  // Products (Phase 3)
  PRODUCT_CREATED = 'PRODUCT_CREATED',
  PRODUCT_UPDATED = 'PRODUCT_UPDATED',
  PRODUCT_DELETED = 'PRODUCT_DELETED',
  INVENTORY_CHANGED = 'INVENTORY_CHANGED',
  PRICE_CHANGED = 'PRICE_CHANGED',
  // Checkout & Payment (Phase 6)
  CHECKOUT_CREATED = 'CHECKOUT_CREATED',
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  INVENTORY_RESERVED = 'INVENTORY_RESERVED',
  INVENTORY_RELEASED = 'INVENTORY_RELEASED',
  // Cart (Phase 5)
  CART_CREATED = 'CART_CREATED',
  CART_UPDATED = 'CART_UPDATED',
  CART_ITEM_ADDED = 'CART_ITEM_ADDED',
  CART_ITEM_REMOVED = 'CART_ITEM_REMOVED',
  CART_CLEARED = 'CART_CLEARED',
  // Orders (Phase 4+)
  ORDER_CREATED = 'ORDER_CREATED',
  ORDER_ACCEPTED = 'ORDER_ACCEPTED',
  ORDER_PREPARING = 'ORDER_PREPARING',
  ORDER_READY_FOR_PICKUP = 'ORDER_READY_FOR_PICKUP',
  ORDER_ASSIGNED = 'ORDER_ASSIGNED',
  ORDER_PICKED_UP = 'ORDER_PICKED_UP',
  ORDER_OUT_FOR_DELIVERY = 'ORDER_OUT_FOR_DELIVERY',
  ORDER_DELIVERED = 'ORDER_DELIVERED',
  ORDER_COMPLETED = 'ORDER_COMPLETED',
  ORDER_CANCELLED = 'ORDER_CANCELLED',
  ORDER_REFUNDED = 'ORDER_REFUNDED',
  PAYMENT_COMPLETED = 'PAYMENT_COMPLETED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  // Store (Phase 2+)
  STORE_SUBMITTED = 'STORE_SUBMITTED',
  STORE_APPROVED = 'STORE_APPROVED',
  STORE_REJECTED = 'STORE_REJECTED',
  STORE_SUSPENDED = 'STORE_SUSPENDED',
  // Rider (Phase 8)
  RIDER_APPROVED = 'RIDER_APPROVED',
  RIDER_REJECTED = 'RIDER_REJECTED',
  RIDER_ASSIGNED = 'RIDER_ASSIGNED',
  RIDER_ACCEPTED = 'RIDER_ACCEPTED',
  DELIVERY_FAILED = 'DELIVERY_FAILED',
}
