/** Apple startup images — generated by scripts/generate-pwa-assets.mjs */
export const APPLE_SPLASH_LINKS = [
  { media: '(device-width: 430px) and (device-height: 932px)', href: '/pwa/splash/iphone-15-pro.png' },
  { media: '(device-width: 393px) and (device-height: 852px)', href: '/pwa/splash/iphone-14.png' },
  { media: '(device-width: 390px) and (device-height: 844px)', href: '/pwa/splash/iphone-13.png' },
  { media: '(device-width: 375px) and (device-height: 812px)', href: '/pwa/splash/iphone-x.png' },
  { media: '(device-width: 768px) and (device-height: 1024px)', href: '/pwa/splash/ipad.png' },
  { media: '(min-width: 1024px)', href: '/pwa/splash/desktop.png' },
] as const;
