ALTER TYPE "MerchantOnboardingStepKey" ADD VALUE IF NOT EXISTS 'VERIFY';
ALTER TYPE "MerchantOnboardingStepKey" ADD VALUE IF NOT EXISTS 'BUSINESS';
ALTER TYPE "MerchantOnboardingStepKey" ADD VALUE IF NOT EXISTS 'STORE';
ALTER TYPE "MerchantOnboardingStepKey" ADD VALUE IF NOT EXISTS 'LOCATION';
ALTER TYPE "MerchantOnboardingStepKey" ADD VALUE IF NOT EXISTS 'DELIVERY';
ALTER TYPE "MerchantOnboardingStepKey" ADD VALUE IF NOT EXISTS 'CATEGORIES';
ALTER TYPE "MerchantOnboardingStepKey" ADD VALUE IF NOT EXISTS 'GST_PAN';
ALTER TYPE "MerchantOnboardingStepKey" ADD VALUE IF NOT EXISTS 'BANK';
