import {
  LayoutDashboard,
  Store,
  ShoppingBag,
  Users,
  Activity,
  Shield,
  Tags,
  FolderTree,
  Bike,
  Banknote,
  Percent,
  Star,
  Tag,
  BarChart3,
  Radio,
  Headphones,
  MessageSquare,
  Package,
  Settings,
  MapPin,
  ImageIcon,
  Truck,
  Send,
  Sparkles,
  UtensilsCrossed,
  type LucideIcon,
} from 'lucide-react';

export interface NavItem {
  href: string;
  label: string;
  icon: LucideIcon;
  /** Extra terms the command palette matches on, beyond the label. */
  keywords?: string;
}

export const NAV: NavItem[] = [
  { href: '/dashboard', label: 'Overview', icon: LayoutDashboard, keywords: 'home dashboard' },
  { href: '/analytics', label: 'Analytics', icon: BarChart3, keywords: 'reports metrics charts' },
  { href: '/control-room', label: 'Control Room', icon: Radio, keywords: 'live ops' },
  { href: '/stores', label: 'Stores', icon: Store, keywords: 'merchants shops sellers' },
  { href: '/restaurant-ops', label: 'Restaurant Ops', icon: UtensilsCrossed, keywords: 'food kitchen menu' },
  { href: '/merchant-applications', label: 'Applications', icon: Store, keywords: 'onboarding kyc merchant signup' },
  { href: '/reviews', label: 'Reviews', icon: Star, keywords: 'ratings feedback' },
  { href: '/promotions', label: 'Promotions', icon: Tag, keywords: 'offers coupons discounts' },
  { href: '/campaigns', label: 'Campaigns', icon: Tag, keywords: 'marketing push' },
  { href: '/rewards', label: 'Rewards & Wallet', icon: Tag, keywords: 'cashback loyalty points' },
  { href: '/catalog', label: 'Catalog', icon: FolderTree, keywords: 'products categories' },
  { href: '/catalog/image-coverage', label: 'Image Coverage', icon: ImageIcon, keywords: 'photos missing images' },
  { href: '/ai-product-usage', label: 'AI Product Usage', icon: Sparkles, keywords: 'ai credits ocr' },
  { href: '/merchant-ai-wallets', label: 'Merchant AI Wallets', icon: Sparkles, keywords: 'ai balance credits topup' },
  { href: '/category-requests', label: 'Category Requests', icon: Tags },
  { href: '/inventory', label: 'Inventory', icon: Shield, keywords: 'stock' },
  { href: '/orders', label: 'Orders', icon: ShoppingBag, keywords: 'sales purchases' },
  { href: '/orders/unassigned', label: 'Unassigned', icon: Bike, keywords: 'orders no rider' },
  { href: '/logistics', label: 'Logistics', icon: Truck, keywords: 'shadowfax delivery shipping courier' },
  { href: '/fleet/live', label: 'Fleet Live', icon: Activity, keywords: 'riders map tracking' },
  { href: '/operations/map', label: 'Operations Map', icon: Activity, keywords: 'map live' },
  { href: '/riders/live', label: 'Riders Live', icon: Bike, keywords: 'delivery boys' },
  { href: '/settlements', label: 'Settlements', icon: Banknote, keywords: 'payouts merchant money' },
  { href: '/finance', label: 'Finance', icon: Banknote, keywords: 'money cod ledger revenue' },
  { href: '/finance/commission', label: 'Commission Rules', icon: Percent, keywords: 'take rate fees' },
  { href: '/compliance', label: 'Compliance', icon: Shield, keywords: 'gst legal fssai' },
  { href: '/trust-safety', label: 'Trust & Safety', icon: Shield, keywords: 'fraud abuse' },
  { href: '/support-center', label: 'Support Center', icon: Headphones, keywords: 'tickets helpdesk complaints' },
  { href: '/whatsapp', label: 'WhatsApp Inbox', icon: MessageSquare, keywords: 'chat messages wa conversations reply' },
  { href: '/whatsapp/broadcasts', label: 'WhatsApp Broadcast', icon: Send, keywords: 'bulk campaign blast csv template marketing' },
  { href: '/crm', label: 'CRM & Growth', icon: BarChart3, keywords: 'customers retention' },
  { href: '/merchant-success', label: 'Merchant Success', icon: Star },
  { href: '/fulfillment-network', label: 'Fulfillment Network', icon: Activity, keywords: 'dark store warehouse' },
  { href: '/locations', label: 'Master Locations', icon: MapPin, keywords: 'pincode city state' },
  { href: '/delivery-coverage', label: 'Delivery Coverage', icon: MapPin, keywords: 'radius serviceability pincode' },
  { href: '/supply-chain', label: 'Supply Chain', icon: Package, keywords: 'procurement vendors' },
  { href: '/expansion', label: 'Expansion', icon: Radio, keywords: 'new cities launch' },
  { href: '/ai-commerce', label: 'AI Commerce', icon: BarChart3 },
  { href: '/fleet', label: 'Fleet OS', icon: Bike, keywords: 'riders vehicles' },
  { href: '/ads', label: 'Ads', icon: Tag, keywords: 'sponsored advertising' },
  { href: '/membership', label: 'Membership', icon: Star, keywords: 'subscription plus prime' },
  { href: '/corporate', label: 'Corporate', icon: Users, keywords: 'b2b bulk' },
  { href: '/seo', label: 'SEO & GEO', icon: BarChart3 },
  { href: '/users', label: 'Users', icon: Users, keywords: 'accounts roles staff admins' },
  { href: '/monitoring', label: 'Monitoring', icon: Activity, keywords: 'health logs uptime' },
  { href: '/settings/security', label: 'Security', icon: Settings, keywords: 'settings 2fa password' },
];
