export const EMAIL_COLORS = {
  primary: '#16A34A',
  secondary: '#0F172A',
  muted: '#64748B',
  background: '#F8FAFC',
  white: '#FFFFFF',
} as const;

export const EMAIL_LOGO_URL = 'https://jebdekho.com/logo.png';

export const EMAIL_TEMPLATE = {
  OTP: 'otp',
  WELCOME: 'welcome',
  MERCHANT_WELCOME: 'merchant_welcome',
  FRANCHISE_WELCOME: 'franchise_welcome',
  RIDER_WELCOME: 'rider_welcome',
  ORDER_CONFIRMATION: 'order_confirmation',
  PAYMENT_SUCCESS: 'payment_success',
  PAYMENT_FAILED: 'payment_failed',
  MERCHANT_ACCEPTED: 'merchant_accepted',
  ORDER_REJECTED: 'merchant_rejected_cancelled',
  DELIVERY_ASSIGNED: 'delivery_assigned_picked_up',
  ORDER_DELIVERED: 'order_delivered',
  REFUND_INITIATED: 'refund_initiated',
  PASSWORD_RESET: 'password_reset',
  SUPPORT_TICKET: 'support_ticket',
  REFUND: 'refund',
  GST_INVOICE: 'gst_invoice',
  TEST: 'test',
  ADMIN_WELCOME: 'admin_welcome',
  ADMIN_PASSWORD_RESET: 'admin_password_reset',
  ADMIN_SECURITY_ALERT: 'admin_security_alert',
  ADMIN_NEW_DEVICE: 'admin_new_device',
  ADMIN_NEW_MERCHANT_APPLICATION: 'admin_new_merchant_application',
  ADMIN_DOCUMENTS_SUBMITTED: 'admin_documents_submitted',
  ADMIN_REFUND_REQUEST: 'admin_refund_request',
  ADMIN_DELIVERY_FAILED_DELAYED: 'admin_delivery_failed_delayed',
  ADMIN_REPEATED_PAYMENT_FAILURE: 'admin_repeated_payment_failure',
  ADMIN_SUPPORT_TICKET_CREATED: 'admin_support_ticket_created',
  MERCHANT_APPLICATION_RECEIVED: 'merchant_application_received',
  MERCHANT_APPROVED: 'merchant_approved',
  MERCHANT_REJECTED: 'merchant_rejected',
  MERCHANT_MORE_DOCS_REQUIRED: 'merchant_more_docs_required',
  MERCHANT_NEW_ORDER: 'merchant_new_order',
  MERCHANT_ORDER_CANCELLED: 'merchant_order_cancelled',
  MERCHANT_SETTLEMENT_INITIATED: 'merchant_settlement_initiated',
  MERCHANT_SETTLEMENT_COMPLETED: 'merchant_settlement_completed',
} as const;

export type EmailTemplateCode = (typeof EMAIL_TEMPLATE)[keyof typeof EMAIL_TEMPLATE];
